
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "About Page",
    description: "This is About Page",
  };

const AboutPage = () => {

    return (
        <>
        <h1>About Page</h1>
        </>
    )
}

export default AboutPage

//METADATA
//elemets <head> , title: About page and meta name content and description: This is About Page
//page itself data ko data ho. METADATA ma pageko data paunna sakin6
//yo METADATA Google search engine lai chahin6. first ma title and description her6.
//METADATA page and Layout dina mil6
//title vitra 3 ta absolute , default and template dina mil6

// export const metadata: Metadata = {
//     title: {
//      default: "Default title",
//      template: "%s | Daraz",
//     },
//      description: "Generated by create next app",
//    };
   
//hamile main layout ma yo code %s | Daraz lekhepaci ... for eg. 
// export const metadata: Metadata = {
//     title: "About Page",
//     description: "This is About Page",
//   };

//about pageko title and layout ko pageko template bata . title About page | Daraz aau6
//yesto nagarne absolute yei title lekhnako lagi Login pagema eg. 6

// export const metadata: Metadata = {
//     title: {
//      absolute: "Loign title"
//     },
//      description: "Generated by create next app",
//    };

//yo garda layout ko title ignore garea login kai title aau6