import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
 title: {
  default: "Default title",
  template: "%s | Daraz",
 },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body>
        <header> This is header</header>
        
        {children}
        <footer> This is footer</footer>
      </body>
    </html>
  );
}

//METADATA

//inspect the page , <head> , title and meta name content and description
//yo  METADATA  App LAYOUT ma rakheko 6, so sabai page ma lagne vayo. certain page ma pani METADAT dina mil6
//example - in About page

//METADATA vayeko component lai "use client " lekhera client component banauna mildaina.
//METADATA server component ma matra use garna mil6

//PRODUCTION SERVER ERROR
//Application error: a server-side exception has occurred (see the server logs for more information).
//Digest: 797007968

//yesto error nadekhauna , header and footer include garera production server ma pani ramroi error dekhauna sakin6.
