import { Metadata } from "next";

export const metadata: Metadata = {
    title: {
     absolute: "Loign title"
    },
     description: "Generated by create next app",
   };

const LoginPage = () => {
    return (
        <>
        <h1>Login Page</h1>
        </>
    )   
}

export default LoginPage

//(auth) yo garda route grouping hun6. /route/login garna parena.
// http://localhost:3000/login yetikai hun6

//